lambda_role = iam.Role(
    self,
    "LambdaAnalyticsRole",
    assumed_by=iam.ServicePrincipal("lambda.amazonaws.com"),
    managed_policies=[
        iam.ManagedPolicy.from_aws_managed_policy_name("service-role/AWSLambdaBasicExecutionRole"),
        iam.ManagedPolicy.from_aws_managed_policy_name("CloudWatchLogsFullAccess")
    ],
    inline_policies={
        "CostExplorerAnalyticsPolicy": iam.PolicyDocument(
            statements=[
                iam.PolicyStatement(
                    effect=iam.Effect.ALLOW,
                    actions=[
                        "ce:GetCostAndUsage",
                        "ce:GetDimensionValues",
                        "ce:GetMetricsAndUsage",
                        "ce:ListCostCategoryDefinitions",
                        "ce:GetUsageReport",
                        "ce:GetAnomalyDetectors",
                        "ce:GetAnomalySubscriptions"
                    ],
                    resources=["*"]
                ),
                iam.PolicyStatement(
                    effect=iam.Effect.ALLOW,
                    actions=[
                        "cloudwatch:PutMetricData",
                        "logs:StartQuery",
                        "logs:GetQueryResults",
                        "vpc-lattice:GetService",
                        "vpc-lattice:GetServiceNetwork",
                        "vpc-lattice:ListServices",
                        "vpc-lattice:ListServiceNetworks"
                    ],
                    resources=["*"]
                )
            ]
        )
    }
)
