role.addToPolicy(new iam.PolicyStatement({
  effect: iam.Effect.ALLOW,
  actions: [
    'ssm:Describe*',
    'ssm:Get*',
    'ssm:List*',
    'ec2:Describe*',
    'ec2:Get*',
    'ec2:List*',
    'rds:Describe*',
    'rds:List*',
    's3:Get*',
    's3:List*',
    'lambda:List*',
    'lambda:Get*',
    'states:List*',
    'states:Describe*',
    'events:List*',
    'events:Describe*',
    'cloudwatch:Describe*',
    'cloudwatch:Get*',
    'cloudwatch:List*',
    'sns:List*',
    'sns:Get*',
    'logs:Describe*',
    'logs:Get*',
    'logs:List*',
    'backup:List*',
    'backup:Describe*'
    // Write permissions have been removed from the workflow level and should be assigned at the job level as appropriate.
  ],
  resources: ['*']
}));
// NOTE: Write permissions have been removed from the workflow level and should be assigned at the job level as appropriate.